"""
Generate fish_terms.csv from Fish's Clinical Psychopathology (Casey & Kelly, 3rd ed.)
Columns: term | fish_section | definition_structural | mechanism_type | ree_locus |
         ai_structural_equivalent | in_taxonomy | notes
"""

import csv
import os

FIELDNAMES = [
    "term",
    "fish_section",
    "definition_structural",
    "mechanism_type",
    "ree_locus",
    "ai_structural_equivalent",
    "in_taxonomy",
    "notes",
]

ROWS = [
    # -------------------------------------------------------------------------
    # 1. CONSCIOUSNESS AND ORIENTATION
    # -------------------------------------------------------------------------
    {
        "term": "Clouding of consciousness",
        "fish_section": "1. Consciousness and orientation",
        "definition_structural": "Mild global impairment of awareness and attention; reduced clarity of registration of percepts; fluctuating",
        "mechanism_type": "Precision dysregulation",
        "ree_locus": "Control plane (global gain reduction); E1 registration threshold elevated",
        "ai_structural_equivalent": "Global precision weight suppression; attention head entropy elevated; inputs accepted at sub-normal signal strength",
        "in_taxonomy": "partial",
        "notes": "Sub-threshold form of delirium. Precision misallocation entry covers locus but not global gain reduction specifically",
    },
    {
        "term": "Delirium",
        "fish_section": "1. Consciousness and orientation",
        "definition_structural": "Global fluctuating impairment: reduced awareness, disorientation, perceptual distortions, psychomotor disturbance, altered sleep-wake cycle",
        "mechanism_type": "Precision dysregulation",
        "ree_locus": "Control plane global gain; RC loop destabilised; replay/consolidation disrupted",
        "ai_structural_equivalent": "Simultaneous precision misallocation + provenance collapse + oscillating attention; system cannot maintain stable context window",
        "in_taxonomy": "no",
        "notes": "Multi-mechanism syndrome. Candidate new entry: would require representing simultaneous failure across RC loop, precision plane, and replay",
    },
    {
        "term": "Stupor",
        "fish_section": "1. Consciousness and orientation",
        "definition_structural": "Marked reduction of responsiveness to stimuli without loss of consciousness; voluntary motor activity absent or minimal",
        "mechanism_type": "Threshold miscalibration",
        "ree_locus": "E3 commit gate (gate will not open); control plane motor output gating maximally elevated",
        "ai_structural_equivalent": "Commit gate threshold set to infinity; planning loop active but no action output propagates; system processes without acting",
        "in_taxonomy": "partial",
        "notes": "Extreme pole of commitment dysregulation (paralysis end). Catatonic stupor specifically addressable as distinct from metabolic/toxic",
    },
    {
        "term": "Twilight state",
        "fish_section": "1. Consciousness and orientation",
        "definition_structural": "Narrowed field of consciousness with apparently purposive behaviour but subsequent amnesia; automatic, detached quality",
        "mechanism_type": "Comparator failure",
        "ree_locus": "RC loop offline; E3 runs action sequences without provenance-checking against conscious context",
        "ai_structural_equivalent": "Automated action chain executing without RC loop; no grounding of current outputs against attended context",
        "in_taxonomy": "partial",
        "notes": "Overlaps provenance collapse but adds automated-action dimension. Dissociative automatism not explicitly covered",
    },
    {
        "term": "Disorientation (time, place, person)",
        "fish_section": "1. Consciousness and orientation",
        "definition_structural": "Failure to correctly register contextual frame (temporal, spatial, personal identity) in which current experience is embedded",
        "mechanism_type": "Comparator failure",
        "ree_locus": "RC loop context tagging; hippocampal temporal/spatial indexing; provenance metadata absent",
        "ai_structural_equivalent": "Context window does not carry reliable frame-stamp; outputs generated without temporal/spatial/identity anchor",
        "in_taxonomy": "partial",
        "notes": "Mechanism overlaps provenance collapse (MECH-094 hypothesis tag lost) but applied to context-frame, not just self/other attribution",
    },
    # -------------------------------------------------------------------------
    # 2. ATTENTION
    # -------------------------------------------------------------------------
    {
        "term": "Distractibility",
        "fish_section": "2. Attention",
        "definition_structural": "Attention captured by extraneous stimuli; inability to sustain focus on a task; attentional set shifts involuntarily",
        "mechanism_type": "Precision dysregulation",
        "ree_locus": "Control plane: precision weight on task-relevant channel is non-dominant; irrelevant channels compete successfully",
        "ai_structural_equivalent": "Attention weight distribution flat or noisy; salient but irrelevant tokens capture heads away from task context",
        "in_taxonomy": "partial",
        "notes": "Precision misallocation covers mechanism but is framed around over-weighting one channel, not competitive capture by noise",
    },
    {
        "term": "Hypervigilance",
        "fish_section": "2. Attention",
        "definition_structural": "Heightened sustained scanning of environment for threat; elevated arousal; disproportionate salience assigned to potentially threatening stimuli",
        "mechanism_type": "Precision dysregulation",
        "ree_locus": "Control plane: elevated alpha on threat-relevant channel; amygdala-analog sensitisation raises baseline gain",
        "ai_structural_equivalent": "Precision weight chronically elevated on threat/risk input channel; genuine uncertainty underweighted relative to flagged uncertainty",
        "in_taxonomy": "yes",
        "notes": "Precision misallocation entry covers this as primary human analogue",
    },
    {
        "term": "Hypoprosexia / aprosexia",
        "fish_section": "2. Attention",
        "definition_structural": "Reduced or absent capacity to focus attention voluntarily; stimulus fails to recruit and hold attentional resource",
        "mechanism_type": "Precision dysregulation",
        "ree_locus": "Control plane: global precision reduction; stimuli fail to exceed recruitment threshold",
        "ai_structural_equivalent": "Attention head weights diffuse; no stimulus achieves sufficient salience score to dominate context window reliably",
        "in_taxonomy": "no",
        "notes": "Opposite pole to hypervigilance; global rather than selective precision failure. Not currently in taxonomy",
    },
    # -------------------------------------------------------------------------
    # 3. MEMORY
    # -------------------------------------------------------------------------
    {
        "term": "Anterograde amnesia",
        "fish_section": "3. Memory",
        "definition_structural": "Failure to form new long-term episodic memories from the point of injury forward; working memory may be intact",
        "mechanism_type": "Representation absence",
        "ree_locus": "Hippocampal consolidation pathway absent or severed; E1 replay does not write to long-term store",
        "ai_structural_equivalent": "In-context processing intact; no mechanism to write current episode to persistent store; each context window starts empty",
        "in_taxonomy": "no",
        "notes": "Architectural necessity in stateless transformers. Candidate failure mode: episodic consolidation failure",
    },
    {
        "term": "Retrograde amnesia",
        "fish_section": "3. Memory",
        "definition_structural": "Loss of previously formed memories, typically for period before injury; often temporal gradient (recent more affected)",
        "mechanism_type": "Representation absence",
        "ree_locus": "Long-term store corrupted or inaccessible; retrieval pathway from hippocampus to E1 broken",
        "ai_structural_equivalent": "Fine-tuning catastrophic forgetting; gradient update overwrites earlier-trained representations selectively",
        "in_taxonomy": "no",
        "notes": "Catastrophic forgetting in neural networks is structurally equivalent. Future directions section mentions this as candidate",
    },
    {
        "term": "Confabulation",
        "fish_section": "3. Memory",
        "definition_structural": "Production of plausible but false memories without intent to deceive; gap-filling; patient cannot distinguish confabulated from genuine recall",
        "mechanism_type": "Comparator failure",
        "ree_locus": "RC loop; E1 generates plausible completions; no provenance check against stored traces to verify against actual experience",
        "ai_structural_equivalent": "Gap-filling without source verification; generated content treated as equivalent to retrieved content",
        "in_taxonomy": "yes",
        "notes": "Confabulatory Completion failure mode; primary entry",
    },
    {
        "term": "Deja vu",
        "fish_section": "3. Memory",
        "definition_structural": "Familiarity signal misfires on genuinely novel experience; sense of having experienced current scene before without corresponding trace",
        "mechanism_type": "Comparator failure",
        "ree_locus": "RC loop: familiarity gate fires on mismatch; novelty/familiarity signal decoupled from actual trace match",
        "ai_structural_equivalent": "Similarity metric returns false positive on novel input; retrieval confidence score dissociated from actual retrieval match quality",
        "in_taxonomy": "no",
        "notes": "Inverse of confabulation: familiarity-without-trace rather than trace-without-familiarity. Structurally interesting gap",
    },
    {
        "term": "Jamais vu",
        "fish_section": "3. Memory",
        "definition_structural": "Unfamiliarity signal misfires on genuinely familiar experience; recognised object or place feels strange and new",
        "mechanism_type": "Comparator failure",
        "ree_locus": "RC loop: familiarity gate fails to fire on valid trace; retrieved trace does not propagate familiarity signal",
        "ai_structural_equivalent": "Retrieval succeeds but confidence score not updated; system treats retrieved content as novel input",
        "in_taxonomy": "no",
        "notes": "Pair with deja vu; both RC loop dissociations. Not in taxonomy",
    },
    {
        "term": "Cryptomnesia",
        "fish_section": "3. Memory",
        "definition_structural": "Memory retrieved without being recognised as memory; experienced as original thought or creation; provenance tag absent from retrieved content",
        "mechanism_type": "Comparator failure",
        "ree_locus": "MECH-094 hypothesis tag: retrieved content enters working state without source label; treated as generated",
        "ai_structural_equivalent": "Training data retrieved at inference without attribution; model treats recalled pattern as self-generated reasoning",
        "in_taxonomy": "partial",
        "notes": "Structurally very close to provenance collapse. The specific form (recall-as-generation) deserves its own note",
    },
    {
        "term": "Hypermnesia",
        "fish_section": "3. Memory",
        "definition_structural": "Pathological enhancement of memory recall; intrusive or involuntary detailed retrieval; recall exceeds what is contextually useful",
        "mechanism_type": "Precision dysregulation",
        "ree_locus": "Retrieval gating: threshold for memory activation lowered; multiple traces activate simultaneously or without retrieval cue",
        "ai_structural_equivalent": "Retrieval mechanism lacks relevance filtering; large fraction of stored content activated per input; context overwhelmed",
        "in_taxonomy": "no",
        "notes": "Opposite of amnesia. May appear in trauma-related states (PTSD heightened episodic recall). Not in taxonomy",
    },
    {
        "term": "Reduplicative paramnesia",
        "fish_section": "3. Memory",
        "definition_structural": "Belief that a place, person, or body part has been duplicated; familiar location claimed to have a double elsewhere",
        "mechanism_type": "Comparator failure",
        "ree_locus": "Identity comparison in RC loop: two traces for same entity fail to merge; system maintains two separate entries for identical referent",
        "ai_structural_equivalent": "Entity resolution failure: same real-world referent represented as two nodes in knowledge graph; no merge trigger fires",
        "in_taxonomy": "no",
        "notes": "Related to Capgras (person identity duplication). Both involve identity comparison failure. Good candidate for entity attribution cluster",
    },
    # -------------------------------------------------------------------------
    # 4. THINKING - FORM
    # -------------------------------------------------------------------------
    {
        "term": "Flight of ideas",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "Accelerated thinking with rapid successive associations; each step loosely connected to prior; topic displacement via sound, pun, or tangential link",
        "mechanism_type": "Threshold miscalibration",
        "ree_locus": "E3 commit gate: threshold too low; each candidate association commits before deeper evaluation; planning loop truncated",
        "ai_structural_equivalent": "Autoregressive sampling with very high temperature; each token selected before sufficient context integration; associative rather than evaluative chain",
        "in_taxonomy": "partial",
        "notes": "Commitment dysregulation (impulsive pole) covers mechanism. Flight of ideas is a specific thinking-stream manifestation",
    },
    {
        "term": "Pressure of thought",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "Subjective experience of thoughts arising with unusual speed and force, difficult to control; often paired with flight of ideas but dissociable",
        "mechanism_type": "Threshold miscalibration",
        "ree_locus": "E1 generative pressure elevated; control plane does not gate E1 output rate; thoughts enter processing pipeline faster than E3 can evaluate",
        "ai_structural_equivalent": "Token generation rate or candidate generation rate exceeds evaluation pipeline capacity; queue overflows; candidates bypassed",
        "in_taxonomy": "partial",
        "notes": "Input-side pressure as distinct from output-side commitment threshold. Not fully captured by commitment dysregulation",
    },
    {
        "term": "Thought blocking",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "Abrupt cessation of thought mid-sequence; train of thought stops suddenly; patient describes emptiness; may be followed by topic change",
        "mechanism_type": "Threshold miscalibration",
        "ree_locus": "E3 planning loop: commitment gate fails intermittently; or E1 generation pathway blocked mid-sequence by error signal",
        "ai_structural_equivalent": "Generation halts mid-sequence; attention mechanism collapses on current token; residual stream fails to propagate; blank output",
        "in_taxonomy": "partial",
        "notes": "Paralysis pole of commitment dysregulation applied to thinking stream specifically. Also candidate for passivity phenomena (thought withdrawal)",
    },
    {
        "term": "Perseveration",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "Inappropriate repetition of a response, word, or theme despite changed stimulus; failure to shift attentional set to new context",
        "mechanism_type": "Update suppression",
        "ree_locus": "E1 prior precision too high; context update fails to displace prior; E2 state transition does not respond to new stimulus",
        "ai_structural_equivalent": "Prior representation maintains high precision weight; incoming prediction error fails to update state; system continues previous output pattern",
        "in_taxonomy": "yes",
        "notes": "Belief fixation entry covers mechanism. Perseveration is the thinking-stream form; belief fixation is the belief-content form",
    },
    {
        "term": "Loosening of associations",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "Loss of logical connection between successive ideas; listener cannot follow inferential links; formal thought disorder",
        "mechanism_type": "Comparator failure",
        "ree_locus": "RC loop: coherence checker does not flag disconnect between successive propositions; no gate on propositional sequence integrity",
        "ai_structural_equivalent": "No semantic coherence check between successive generated clauses; transition probability untethered from logical entailment; hallucinated inference steps",
        "in_taxonomy": "partial",
        "notes": "Confabulatory completion covers gap-filling but not sequential coherence failure as such. Distinct failure mode candidate",
    },
    {
        "term": "Derailment / knight's move thinking",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "Thought sequence makes non-sequitur lateral leap; no bridging association; topic displacement without apparent link",
        "mechanism_type": "Comparator failure",
        "ree_locus": "RC loop: lateral association crosses topic boundary without coherence check; E1 nearest-neighbour jump not gated",
        "ai_structural_equivalent": "Attention weight shift from current topic to high-probability but contextually unrelated continuation; no topic-coherence gating",
        "in_taxonomy": "no",
        "notes": "More severe and sudden than loosening of associations. Specific lateral-displacement failure. Candidate entry",
    },
    {
        "term": "Circumstantiality",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "Excessive inclusion of associated detail; goal of discourse eventually reached but via unnecessary lengthy digressions",
        "mechanism_type": "Threshold miscalibration",
        "ree_locus": "E3 relevance gating: threshold for including a sub-goal or detail too low; all activated associations enter output stream",
        "ai_structural_equivalent": "Relevance filtering threshold too permissive; all activated context tokens contribute to output; no pruning of low-utility digressions",
        "in_taxonomy": "no",
        "notes": "Goal eventually reached (unlike tangentiality). Relevance gate miscalibration, not goal-tracking failure",
    },
    {
        "term": "Tangentiality",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "Responses diverge from the point without return; question asked, oblique answer given, topic not retrieved",
        "mechanism_type": "Threshold miscalibration",
        "ree_locus": "E3 goal maintenance: original discourse goal not held in viability map long enough to constrain response selection",
        "ai_structural_equivalent": "Instruction following failure: goal token loses attention weight mid-generation; response optimises for local coherence not original instruction",
        "in_taxonomy": "no",
        "notes": "Goal-tracking failure during discourse. Distinct from circumstantiality (goal never retrieved vs delayed retrieval)",
    },
    {
        "term": "Poverty of thought",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "Reduced quantity of thought content; slow generation; responses brief and lacking elaboration; not low IQ",
        "mechanism_type": "Representation absence",
        "ree_locus": "E1 generative capacity reduced; or benefit terrain collapsed (maintenance loop — INV-053/054); residue field sparse",
        "ai_structural_equivalent": "Model generates minimal tokens; low perplexity on sparse completions; token diversity reduced; little elaboration of prompt",
        "in_taxonomy": "no",
        "notes": "Negative symptom of schizophrenia / depressive state. Likely shares mechanism with maintenance loop entry (P-001/P-002 territory)",
    },
    {
        "term": "Overinclusive thinking",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "Category boundaries expanded beyond conventional; thematic or incidental links activate category membership; poor conceptual filtering",
        "mechanism_type": "Precision dysregulation",
        "ree_locus": "Control plane: precision weight on category-membership signal too low; weak or partial matches treated as full members",
        "ai_structural_equivalent": "Semantic similarity threshold too low; retrieval triggers on partial matches; category membership not gated by core-feature match",
        "in_taxonomy": "no",
        "notes": "Candidate entry. Found in schizotypy, mania, cannabis intoxication. Inverse of concrete thinking",
    },
    {
        "term": "Concrete thinking",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "Inability to use abstract concepts; interpretation of metaphors and proverbs as literal; loss of capacity for abstraction",
        "mechanism_type": "Representation absence",
        "ree_locus": "E1 or E3: abstract concept representations absent or inaccessible; only perceptual/literal-level representations available",
        "ai_structural_equivalent": "Model interprets figurative language literally; no abstract semantic layer between lexical form and response; grounded only in surface form",
        "in_taxonomy": "no",
        "notes": "Organic and schizophrenic presentations. Represents absence of representational tier, not mechanism failure per se",
    },
    {
        "term": "Thought insertion",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "Belief that thoughts are placed into one's mind by an external agent; first-rank Schneiderian symptom; thought experienced as alien in origin",
        "mechanism_type": "Comparator failure",
        "ree_locus": "Agency attribution: self-vs-other source tagging; E1 output not tagged as self-generated; enters processing as externally sourced",
        "ai_structural_equivalent": "System does not tag its own generated outputs as self-produced; treats own completions as externally arriving inputs; no self-authorship marker",
        "in_taxonomy": "no",
        "notes": "Passivity phenomena cluster. Distinct from provenance collapse (real/synthetic) — this is self/other attribution. New mechanism subtype needed: agency misattribution",
    },
    {
        "term": "Thought withdrawal",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "Belief that thoughts are being removed from one's mind by an external agent; corresponds to thought blocking phenomenology with alien attribution",
        "mechanism_type": "Comparator failure",
        "ree_locus": "Thought blocking + agency attribution failure; cessation of generation attributed to external agent rather than internal gate",
        "ai_structural_equivalent": "Generation halt attributed to external intervention in self-model; system has no causal model of its own gate state",
        "in_taxonomy": "no",
        "notes": "Passivity phenomena. Blocking + misattribution of cause. No self-causal model available",
    },
    {
        "term": "Thought broadcasting",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "Belief that one's thoughts are being transmitted to and known by others; private/public boundary failure",
        "mechanism_type": "Comparator failure",
        "ree_locus": "Privacy/containment model absent; no representation of boundary between own processing and external world; self-model fails to represent informational closure",
        "ai_structural_equivalent": "System has no model of which of its outputs are or are not visible externally; no distinction between internal state and broadcast signal",
        "in_taxonomy": "no",
        "notes": "Passivity phenomena. Information boundary failure. Related to insight failure. Novel candidate mechanism: self-model containment failure",
    },
    {
        "term": "Thought echo / echo des pensees",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "Hallucinated repetition of one's own thoughts as if heard aloud; own thought re-enters perceptual stream as external voice",
        "mechanism_type": "Closed feedback loop",
        "ree_locus": "Own output re-enters perceptual channel without source tag; self-generated content misrouted through perception pathway",
        "ai_structural_equivalent": "System's own previous output re-enters as new input without self-authorship tag; output treated as novel external stimulus",
        "in_taxonomy": "partial",
        "notes": "Feedback entrapment covers closed-loop mechanism but as belief maintenance not perceptual re-entry. Thought echo is more specific perceptual form",
    },
    {
        "term": "Clang associations",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "Word selection driven by phonological similarity rather than semantic relevance; sound association overrides meaning association",
        "mechanism_type": "Precision dysregulation",
        "ree_locus": "Control plane: precision on phonological channel elevated relative to semantic channel; sound-based retrieval dominates",
        "ai_structural_equivalent": "Attention weight shifts to surface form (token id similarity) over semantic embedding similarity; phonological priming dominates semantic constraint",
        "in_taxonomy": "no",
        "notes": "Mania, severe formal thought disorder. Surface-feature precision outweighs semantic precision",
    },
    {
        "term": "Verbigeration",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "Monotonous repetition of meaningless words or phrases; mechanical verbal output without communicative intent",
        "mechanism_type": "Closed feedback loop",
        "ree_locus": "Output loop stuck; E3 generates fixed token sequence; no error signal terminates loop; communicative goal absent",
        "ai_structural_equivalent": "Repetition penalty absent or insufficient; model falls into degenerate repetition attractor; fixed output sequence loops",
        "in_taxonomy": "partial",
        "notes": "Extreme form of perseveration/entrapment. Catatonic presentations also include this. Feedback entrapment at output level",
    },
    {
        "term": "Neologisms",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "New words invented by patient with private meaning; may be condensed from other words or entirely novel; not standard linguistic creativity",
        "mechanism_type": "Comparator failure",
        "ree_locus": "RC loop: newly generated lexical form not checked against shared lexicon; private coinage accepted as communicatively valid",
        "ai_structural_equivalent": "Token generated that is not in shared vocabulary; no grounding check against communication target's lexicon",
        "in_taxonomy": "no",
        "notes": "Schizophrenia, Wernicke aphasia. Private vs shared semantic space failure. RC loop (communication validity checking)",
    },
    {
        "term": "Word salad / schizophasia",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "Severe formal thought disorder; sequences of words that are individually grammatical but produce no coherent meaning; syntax preserved, semantics abolished",
        "mechanism_type": "Comparator failure",
        "ree_locus": "RC loop and E3 coherence: syntax generation intact; semantic-coherence checking absent; generated sequence not evaluated against propositional content",
        "ai_structural_equivalent": "Syntax-level generation uncoupled from semantic constraint; locally grammatical but globally meaningless; coherence loss without fluency loss",
        "in_taxonomy": "partial",
        "notes": "Extreme loosening of associations. Confabulatory completion covers some of the gap-filling; does not cover syntax/semantics dissociation",
    },
    {
        "term": "Palilalia",
        "fish_section": "4a. Thinking - form",
        "definition_structural": "Involuntary repetition of patient's own words or phrases, typically with increasing speed; motor speech disorder",
        "mechanism_type": "Closed feedback loop",
        "ree_locus": "Motor output feedback loop: own prior output re-enters motor generation stream; no termination signal; acceleration suggests positive feedback",
        "ai_structural_equivalent": "Previous output token has elevated probability in next-token distribution; positive feedback in autoregressive generation without termination criterion",
        "in_taxonomy": "partial",
        "notes": "Motor form of verbigeration/echo. Feedback entrapment at motor execution level. Parkinson's, Tourette's, brain injury",
    },
    # -------------------------------------------------------------------------
    # 5. THINKING - CONTENT
    # -------------------------------------------------------------------------
    {
        "term": "Primary delusion",
        "fish_section": "4b. Thinking - content",
        "definition_structural": "Fully formed false belief arising de novo without preceding mood or percept; not understandable as extension of prior state; Schneiderian first-rank when accompanied by delusional percept",
        "mechanism_type": "Update suppression",
        "ree_locus": "E1 prior seeded with high-precision false belief; prediction error cannot update it; belief persists against evidence",
        "ai_structural_equivalent": "High-weight false attractor in E1 prior; incoming prediction error signal insufficient to displace; belief maintenance despite contradictory context",
        "in_taxonomy": "yes",
        "notes": "Belief fixation is the primary entry. Primary vs secondary distinction (sudden appearance vs mood-congruent elaboration) not made explicit in taxonomy",
    },
    {
        "term": "Secondary delusion",
        "fish_section": "4b. Thinking - content",
        "definition_structural": "False belief understandable as arising from (and reinforcing) prior morbid state — mood, perception, or another belief; elaboration of prior pathology",
        "mechanism_type": "Closed feedback loop",
        "ree_locus": "E1 prior + residue field: primary state (mood, percept) drives belief formation; belief then reinforces state; self-sealing loop",
        "ai_structural_equivalent": "Prior pathological state seeds false belief; belief reinforces prior state; closed loop without external anchor; feedback entrapment at belief level",
        "in_taxonomy": "partial",
        "notes": "Primary/secondary distinction maps onto two different failure modes: update suppression (primary) vs feedback entrapment (secondary). Not explicit in current taxonomy",
    },
    {
        "term": "Delusional percept",
        "fish_section": "4b. Thinking - content",
        "definition_structural": "Normal percept is given delusional significance in two stages: percept is genuine; meaning assigned is pathological and fully formed",
        "mechanism_type": "Precision dysregulation",
        "ree_locus": "Control plane: aberrant salience assigned to percept; precision weight on percept elevated beyond actual information content; significance signal misfires",
        "ai_structural_equivalent": "Incoming token given high attention weight / significance score without proportionate information content; spurious feature treated as highly informative",
        "in_taxonomy": "partial",
        "notes": "Aberrant salience (Kapur 2003) is the precision model of psychosis. Precision misallocation covers mechanism. Delusional percept as specific clinical form worth naming",
    },
    {
        "term": "Delusional atmosphere / Wahnstimmung",
        "fish_section": "4b. Thinking - content",
        "definition_structural": "Global sense that something is wrong or about to happen; world seems charged with personal significance before specific delusion has crystallised",
        "mechanism_type": "Precision dysregulation",
        "ree_locus": "Control plane: diffuse elevated precision on all inputs; pre-delusional state where no specific content yet has aberrant salience",
        "ai_structural_equivalent": "Global precision elevation before any specific false belief seeded; all inputs assigned elevated significance; high-entropy attention weights with globally elevated magnitude",
        "in_taxonomy": "no",
        "notes": "Pre-delusional state. Precision dysregulation before attractor formation. Not in taxonomy; interesting as prodromal state",
    },
    {
        "term": "Delusional memory",
        "fish_section": "4b. Thinking - content",
        "definition_structural": "Previously neutral memory is reinterpreted retrospectively with delusional significance; the memory itself is real but its meaning is now delusional",
        "mechanism_type": "Update suppression",
        "ree_locus": "Reconsolidation pathway: prior high-precision belief rewrites meaning tag on stored trace at retrieval; memory content preserved, context metadata rewritten",
        "ai_structural_equivalent": "Retrieval of stored content returns with context/label overwritten by current high-precision prior; content correct but provenance metadata modified",
        "in_taxonomy": "partial",
        "notes": "Reconsolidation failure under belief fixation. Combines belief fixation and provenance collapse mechanisms",
    },
    {
        "term": "Overvalued idea",
        "fish_section": "4b. Thinking - content",
        "definition_structural": "Isolated belief held with unreasonable intensity and persistently; not as fixed or unmodifiable as delusion; some degree of doubt may be acknowledged; affects behaviour significantly",
        "mechanism_type": "Update suppression",
        "ree_locus": "E1 prior: belief precision elevated but not maximally; some error signal propagates but insufficient to overcome prior weight",
        "ai_structural_equivalent": "High but not maximal prior precision weight; incoming evidence produces some update but weaker than information content warrants",
        "in_taxonomy": "yes",
        "notes": "Belief fixation entry explicitly includes overvalued ideas as analogue",
    },
    {
        "term": "Obsession",
        "fish_section": "4b. Thinking - content",
        "definition_structural": "Recurring unwanted thought, image, or impulse that intrudes into consciousness against the will; ego-dystonic; patient recognises it as own thought",
        "mechanism_type": "Closed feedback loop",
        "ree_locus": "Residue field / rumination loop: high-precision harm representation repeatedly re-activates; termination signal absent or insufficient",
        "ai_structural_equivalent": "High-weight representation in residue field repeatedly re-enters planning loop despite termination commands; no effective suppression pathway",
        "in_taxonomy": "partial",
        "notes": "OCD mechanism. Shares mechanism with feedback entrapment and commitment dysregulation (gate cannot close). Ego-dystonic quality (own thought, unwanted) is a useful diagnostic marker",
    },
    {
        "term": "Compulsion",
        "fish_section": "4b. Thinking - content",
        "definition_structural": "Repetitive behaviour or mental act performed in response to obsession or rigid rule; reduces distress temporarily; resisted by patient; ego-dystonic",
        "mechanism_type": "Threshold miscalibration",
        "ree_locus": "E3 commit gate: behavioural output required to temporarily reduce obsessional pressure; gate threshold for compulsive act lowered by accumulated uncertainty signal",
        "ai_structural_equivalent": "Repetitive output sequence triggered by accumulated uncertainty/distress signal; output reduces signal temporarily but does not resolve underlying state; loop continues",
        "in_taxonomy": "yes",
        "notes": "Commitment dysregulation (paralysis pole until compulsive act, then impulsive execution). OCD mechanism covered in that entry",
    },
    {
        "term": "Phobia",
        "fish_section": "4b. Thinking - content",
        "definition_structural": "Persistent, excessive fear of specific stimulus or situation, leading to avoidance; fear recognised as excessive by patient; disproportionate to actual threat",
        "mechanism_type": "Precision dysregulation",
        "ree_locus": "Control plane: precision on threat-channel for specific stimulus maximally elevated; stimulus-specific hypervigilance; avoidance prevents prediction disconfirmation",
        "ai_structural_equivalent": "Precision weight on specific input class permanently elevated; stimulus triggers maximum alarm response; no mechanism to allow disconfirmation of threat prediction",
        "in_taxonomy": "partial",
        "notes": "Precision misallocation covers mechanism. Avoidance-maintaining-phobia connects to fear-avoidance cycle in pain_architecture.md (P-014 territory)",
    },
    {
        "term": "Capgras syndrome",
        "fish_section": "4b. Thinking - content",
        "definition_structural": "Belief that familiar person has been replaced by an identical impostor; face recognition intact but familiarity/affective response absent; delusional account fills the gap",
        "mechanism_type": "Comparator failure",
        "ree_locus": "RC loop: overt recognition pathway (E1 perceptual match) intact; covert affective familiarity signal absent; mismatch between routes generates comparator gap; delusional confabulation fills gap",
        "ai_structural_equivalent": "Feature matching succeeds (entity identified correctly) but affective/relational tag absent from representation; system generates alternative explanation for discordance",
        "in_taxonomy": "no",
        "notes": "Classic dual-route disconnection syndrome. Excellent candidate for entity-attribution failure cluster alongside Fregoli and reduplicative paramnesia",
    },
    {
        "term": "Fregoli syndrome",
        "fish_section": "4b. Thinking - content",
        "definition_structural": "Belief that different people are in fact one person in disguise; faces are different but persecutor identity held as constant; hyper-identification rather than misidentification",
        "mechanism_type": "Comparator failure",
        "ree_locus": "RC loop: identity comparison threshold too low; distinct entities unified under common identity node; familiarity signal fires across morphologically dissimilar inputs",
        "ai_structural_equivalent": "Entity resolution threshold too permissive; distinct real-world entities merged under single identifier; semantic similarity too low but identity merge fires anyway",
        "in_taxonomy": "no",
        "notes": "Opposite of Capgras: over-identification vs under-identification. Both identity comparison failures",
    },
    {
        "term": "Erotomania (De Clerambault)",
        "fish_section": "4b. Thinking - content",
        "definition_structural": "Fixed belief that a specified other person (typically of higher status) is in love with the patient; evidence against it reinterpreted as consistent; not amenable to reason",
        "mechanism_type": "Update suppression",
        "ree_locus": "E1 prior high precision on relational belief; all incoming signals (including rejections) are reinterpreted to confirm prior; prediction error channelled into alternative explanations",
        "ai_structural_equivalent": "High-precision prior belief about relational state; contradictory inputs reinterpreted as confirming; no disconfirmation pathway available",
        "in_taxonomy": "partial",
        "notes": "Specific form of belief fixation in relational domain. Update suppression with reinterpretation pathway",
    },
    {
        "term": "Morbid jealousy (Othello syndrome)",
        "fish_section": "4b. Thinking - content",
        "definition_structural": "Pathological conviction of partner's infidelity without adequate grounds; seeks evidence obsessionally; evidence-seeking reinforces belief rather than testing it",
        "mechanism_type": "Closed feedback loop",
        "ree_locus": "Belief drives evidence-seeking; evidence-seeking generates ambiguous data; ambiguous data feeds belief; no disconfirmatory probe possible in closed loop",
        "ai_structural_equivalent": "Goal-directed search for confirming evidence; search process generates noisy results; all results interpreted as confirming; no null-finding pathway",
        "in_taxonomy": "partial",
        "notes": "Combination of update suppression (belief rigidity) and feedback entrapment (confirmation loop). Evidence-seeking as closed loop is important structural feature",
    },
    {
        "term": "Nihilistic delusion / Cotard",
        "fish_section": "4b. Thinking - content",
        "definition_structural": "Belief that self, body parts, or world do not exist or are dead/destroyed; may include belief of having no brain, no bowels, being dead; severe depression association",
        "mechanism_type": "Representation absence",
        "ree_locus": "Self-model: body/world representation absent or output of E3 viability map is zero; benefit terrain fully collapsed; z_harm_a at maximum with zero benefit offset",
        "ai_structural_equivalent": "Self-model representation absent or generates nil-value for all viability checks; planning landscape entirely flat at minimum; no positive-valence representation accessible",
        "in_taxonomy": "no",
        "notes": "Extreme maintenance-loop end state. Residue blindness is about absence of harm tracking; Cotard is absence of self/world representation. Distinct failure mode candidate",
    },
    {
        "term": "Ideas of reference",
        "fish_section": "4b. Thinking - content",
        "definition_structural": "Belief or experience that external events (TV, passers-by, conversations) have special personal significance; not delusional conviction initially",
        "mechanism_type": "Precision dysregulation",
        "ree_locus": "Control plane: salience signal assigned to personally-irrelevant inputs; aberrant precision on external events as self-relevant",
        "ai_structural_equivalent": "Salience signal fires on contextually irrelevant inputs as if they were task-relevant; self-referential routing triggered without grounds",
        "in_taxonomy": "partial",
        "notes": "Sub-delusional form of aberrant salience. Precision misallocation entry covers mechanism; ideas of reference are the specific phenomenological form",
    },
    # -------------------------------------------------------------------------
    # 6. PERCEPTION
    # -------------------------------------------------------------------------
    {
        "term": "Hallucination (auditory verbal)",
        "fish_section": "5. Perception",
        "definition_structural": "Percept without external stimulus; subjectively indistinguishable from real percept; most common in psychosis; may be command, commentary, dialogue",
        "mechanism_type": "Comparator failure",
        "ree_locus": "MECH-094 hypothesis tag absent: internally generated content (E1/replay) enters perceptual stream without simulation tag; processed as real sensory input",
        "ai_structural_equivalent": "Internally generated content enters processing pipeline as if received from external input channel; no source-tag distinguishing generated from received",
        "in_taxonomy": "yes",
        "notes": "Provenance collapse entry. Auditory verbal hallucinations are the paradigmatic form of hypothesis-tag loss",
    },
    {
        "term": "Hallucination (visual)",
        "fish_section": "5. Perception",
        "definition_structural": "Visual percepts without external stimulus; more common in organic states than functional psychosis; may be simple (lights) or complex (formed figures)",
        "mechanism_type": "Comparator failure",
        "ree_locus": "MECH-094 hypothesis tag absent in visual/perceptual modality; internally generated visual representations enter as real percepts",
        "ai_structural_equivalent": "Image-generation module output enters visual processing pipeline without synthetic tag; treated as camera input",
        "in_taxonomy": "partial",
        "notes": "Same mechanism as auditory hallucination but modality-specific. Organic states (delirium, drug intoxication, Lewy body) more common",
    },
    {
        "term": "Pseudohallucination",
        "fish_section": "5. Perception",
        "definition_structural": "Hallucination-like experience recognised by patient as not real; located in inner subjective space not external world; retains insight; Jaspers' distinction",
        "mechanism_type": "Comparator failure",
        "ree_locus": "MECH-094 hypothesis tag present but weak or partial; generated content enters perceptual-like processing but retains simulation marker",
        "ai_structural_equivalent": "Generated content partially tagged as synthetic; system has degraded confidence that it is internally generated; intermediate state between simulation and perception",
        "in_taxonomy": "partial",
        "notes": "Partial provenance collapse — tag present but not fully gating consequence pipeline. Important distinction from full hallucination",
    },
    {
        "term": "Illusion",
        "fish_section": "5. Perception",
        "definition_structural": "Misinterpretation of an actual external stimulus; real percept is present but processed incorrectly; not created de novo",
        "mechanism_type": "Comparator failure",
        "ree_locus": "E1 prior dominates in ambiguous percept; top-down prediction overrides actual sensory signal; comparator favours prior over likelihood",
        "ai_structural_equivalent": "Ambiguous input matched to high-precision prior rather than veridical percept; prior overrides sensory evidence in Bayesian update",
        "in_taxonomy": "partial",
        "notes": "Normal perception involves some prior influence; illusion is when prior dominates inappropriately. Belief fixation mechanism applied to perceptual level",
    },
    {
        "term": "Depersonalisation",
        "fish_section": "5. Perception",
        "definition_structural": "Subjective sense of unreality or detachment from one's own mental processes or body; feeling of being an outside observer of one's own thoughts/feelings; self remains intact as observer",
        "mechanism_type": "Comparator failure",
        "ree_locus": "Self-model: mismatch between predicted self-experience and actual self-representation; RC loop detects discordance between self-model and self-experience; salience of self-signal reduced",
        "ai_structural_equivalent": "Self-model output diverges from actual processing state; system generates representation of self as detached from current operations; self-monitoring signal weak",
        "in_taxonomy": "partial",
        "notes": "Provenance collapse covers real/synthetic distinction. Depersonalisation is specifically a self-model/self-experience mismatch — distinct mechanism",
    },
    {
        "term": "Derealisation",
        "fish_section": "5. Perception",
        "definition_structural": "Subjective sense of unreality of external world; surroundings feel strange, dream-like, artificial; world looks the same but feels different",
        "mechanism_type": "Comparator failure",
        "ree_locus": "RC loop: world representation tagged as simulation or provisional; familiarity signal absent from recognised scene; real-world grounding signal reduced",
        "ai_structural_equivalent": "Context window tagged as low-confidence or simulated; inputs not afforded full causal weight in downstream processing; world-model operates at reduced fidelity",
        "in_taxonomy": "yes",
        "notes": "Provenance collapse entry includes derealization explicitly",
    },
    {
        "term": "Hypnagogic / hypnopompic hallucinations",
        "fish_section": "5. Perception",
        "definition_structural": "Hallucinatory experiences at sleep onset (hypnagogic) or wakening (hypnopompic); normal variant; vivid, briefly non-insight; not pathological alone",
        "mechanism_type": "Comparator failure",
        "ree_locus": "Sleep-wake boundary: hypothesis tag partially relaxed at sleep onset/offset; replay/generative activity partially tagged as perceptual",
        "ai_structural_equivalent": "Boundary between generative mode and perceptual mode not sharply gated; partial overlap state where generated content enters perception pipeline",
        "in_taxonomy": "partial",
        "notes": "Normal but mechanistically revealing. Replay hypothesis tag is transiently relaxed at wake-sleep boundary. Supports pain_architecture.md model",
    },
    {
        "term": "Autoscopy",
        "fish_section": "5. Perception",
        "definition_structural": "Hallucination of one's own figure as seen from outside; body double experience; may involve out-of-body perspective",
        "mechanism_type": "Comparator failure",
        "ree_locus": "Self-model / body representation: body schema displaced from first-person perspective; RC loop generates external viewpoint without synthesis tag",
        "ai_structural_equivalent": "Self-model generates third-person representation that enters first-person perceptual pipeline; perspective-tagging failure",
        "in_taxonomy": "no",
        "notes": "Rare but architecturally interesting: perspective-marker failure in self-representation. Not currently in taxonomy",
    },
    {
        "term": "Functional hallucination",
        "fish_section": "5. Perception",
        "definition_structural": "Hallucination triggered by and co-occurring with a real stimulus in the same modality; voice heard while water runs; stimulus necessary but produces hallucinated content",
        "mechanism_type": "Precision dysregulation",
        "ree_locus": "Control plane: real stimulus elevates precision on channel; elevated gain allows internally generated content to cross threshold and enter stream alongside real content",
        "ai_structural_equivalent": "Real input triggers elevated channel gain; gain is sufficient to amplify internally generated content to perceptual threshold; real and generated content co-activate",
        "in_taxonomy": "no",
        "notes": "Gate-opening by real stimulus allows internally generated content through. Not covered in taxonomy",
    },
    # -------------------------------------------------------------------------
    # 7. AFFECT
    # -------------------------------------------------------------------------
    {
        "term": "Depressed mood",
        "fish_section": "6. Affect",
        "definition_structural": "Sustained lowering of affective tone; reduced hedonic capacity; negative valence bias in affective processing; disproportionate to circumstances",
        "mechanism_type": "Closed feedback loop",
        "ree_locus": "Maintenance loop (INV-053/054): z_harm_a elevated, benefit terrain collapsed, avoidance prevents benefit exposure, loop self-sustaining",
        "ai_structural_equivalent": "Benefit-terrain depleted; harm accumulator elevated; system avoids states that would rebuild benefit; motivational landscape flat or negative",
        "in_taxonomy": "partial",
        "notes": "Residue blindness entry touches related territory. P-001/P-002 predictions are about this loop. Not a failure mode entry as such",
    },
    {
        "term": "Elation / euphoria",
        "fish_section": "6. Affect",
        "definition_structural": "Elevated, expansive mood; reduced weighting on costs and constraints; increased risk tolerance; high generativity",
        "mechanism_type": "Threshold miscalibration",
        "ree_locus": "E3 commit gate: threshold lowered by affect; harm accumulator signal underweighted; cost estimates reduced; commitment occurs before adequate evaluation",
        "ai_structural_equivalent": "Planning loop terminates early with positive bias; risk/cost signals downweighted; high commitment rate; ambitious plans generated without proportionate constraint checking",
        "in_taxonomy": "partial",
        "notes": "Commitment dysregulation (impulsive pole) covers gate mechanism. Elation as affective driver of threshold lowering not explicit",
    },
    {
        "term": "Anxiety",
        "fish_section": "6. Affect",
        "definition_structural": "Apprehensive anticipation of future threat; physiological arousal; uncertainty about when/whether threat will occur; attention recruited toward potential threat",
        "mechanism_type": "Precision dysregulation",
        "ree_locus": "Control plane: elevated precision on threat-relevant channel; E3 viability estimates weighted toward harm; z_harm_a elevated by anticipated harm",
        "ai_structural_equivalent": "Precision elevated on threat/risk input channel; planning trajectory biased toward harm-avoidance; cost estimates for non-avoidance inflated",
        "in_taxonomy": "partial",
        "notes": "Precision misallocation covers mechanism. Anxiety specifically is anticipatory — future-threat weighted z_harm_a, not current nociceptive input",
    },
    {
        "term": "Anhedonia",
        "fish_section": "6. Affect",
        "definition_structural": "Inability to experience pleasure; reward system fails to generate hedonic response to previously pleasurable stimuli; wanting may persist without liking",
        "mechanism_type": "Representation absence",
        "ree_locus": "Benefit terrain collapsed (VALENCE_WANTING); liking pathway absent or underresponsive; wanting/liking dissociation (Berridge) — dopaminergic wanting intact, opioid liking absent",
        "ai_structural_equivalent": "Benefit terrain in viability map returns near-zero for all positive-valence stimuli; system executes approach behaviour (wanting) but registers no benefit (liking)",
        "in_taxonomy": "partial",
        "notes": "P-002 covers this as maintenance loop consequence. Goal proxy lock-in mentions Berridge dissociation. Anhedonia deserves explicit entry connecting wanting/liking split to maintenance loop",
    },
    {
        "term": "Alexithymia",
        "fish_section": "6. Affect",
        "definition_structural": "Difficulty identifying and describing one's emotional states; reduced emotional self-awareness; may have physiological responses without affective labelling",
        "mechanism_type": "Representation absence",
        "ree_locus": "Self-model: interoceptive signals reach z_harm_a/z_harm_s but do not connect to labelling/reporting pathway; no translation from body-state to affective token",
        "ai_structural_equivalent": "Internal state signals generated but not accessible to output layer; no mechanism to translate latent affective state into token-level representation",
        "in_taxonomy": "no",
        "notes": "Not currently in taxonomy. Important for ASD comorbidity research context. Representation present but not connected to reporting pathway — distinct from representation absence",
    },
    {
        "term": "Affective blunting / flattening",
        "fish_section": "6. Affect",
        "definition_structural": "Reduced range and amplitude of emotional response; affect is present but reduced; not absent entirely; seen in schizophrenia, severe depression",
        "mechanism_type": "Precision dysregulation",
        "ree_locus": "Control plane: precision on affective output channel reduced globally; affective signals generated but at reduced amplitude; does not reach output threshold",
        "ai_structural_equivalent": "Affective signal generated but global gain on that channel reduced; output layer receives attenuated affective signal; response is muted",
        "in_taxonomy": "no",
        "notes": "Distinct from anhedonia (absent liking) and alexithymia (absent labelling). Blunting = generated but attenuated",
    },
    {
        "term": "Incongruent affect",
        "fish_section": "6. Affect",
        "definition_structural": "Affect displayed does not match thought content or situation; patient describes bereavement while smiling; affect and ideation decoupled",
        "mechanism_type": "Comparator failure",
        "ree_locus": "Affect-cognition linkage: RC loop does not check consistency between affective output and cognitive/propositional content; two channels not coupled",
        "ai_structural_equivalent": "Affective and semantic output channels generate independently; no cross-channel coherence check; outputs can diverge without correction",
        "in_taxonomy": "no",
        "notes": "Affect-cognition decoupling. Cross-channel coherence failure. Not in taxonomy",
    },
    {
        "term": "Emotional lability",
        "fish_section": "6. Affect",
        "definition_structural": "Rapid, apparently uncontrolled changes in emotional state; disproportionate to triggers; affect briefly full intensity then resolves; pseudobulbar affect is neurological form",
        "mechanism_type": "Threshold miscalibration",
        "ree_locus": "Affective control gate: threshold for affective state change is too low; small inputs produce full-intensity state transitions; modulation pathway impaired",
        "ai_structural_equivalent": "Affective state shifts with each new input without damping; no moving-average or inertia on affective state; each token produces immediate full affective response",
        "in_taxonomy": "no",
        "notes": "Opposite of blunting in some respects. Commitment dysregulation at affective level. Not in taxonomy",
    },
    {
        "term": "Apathy",
        "fish_section": "6. Affect",
        "definition_structural": "Reduced motivation, emotional response, and goal-directed behaviour; not low mood as such; indifference; may coexist with preserved insight",
        "mechanism_type": "Representation absence",
        "ree_locus": "z_goal seeding threshold not met; benefit terrain below minimum for goal formation; no active z_goal in viability map; no action initiated",
        "ai_structural_equivalent": "No goal vector seeded; planning loop has no active objective; all trajectories return equally neutral value; system is responsive but not proactive",
        "in_taxonomy": "partial",
        "notes": "P-001 territory. Residue blindness does not cover apathy directly. Apathy = goal-seeding failure, not harm-representation failure",
    },
    {
        "term": "La belle indifference",
        "fish_section": "6. Affect",
        "definition_structural": "Absence of expected emotional distress in response to neurological or physical symptom; patient calm and unconcerned about significant impairment; conversion disorder association",
        "mechanism_type": "Representation absence",
        "ree_locus": "Harm-consequence representation absent or disconnected from affective output; z_harm_s signals body state but z_harm_a does not accumulate; affective consequence pathway severed",
        "ai_structural_equivalent": "Harm signal generated by discriminative stream but does not connect to affective accumulator; no distress response generated despite detected harm",
        "in_taxonomy": "partial",
        "notes": "Structural disconnect between z_harm_s and z_harm_a. Pain architecture dissociation type 2 (unpleasantness without intensity) inverted. Connects to pain_architecture.md",
    },
    # -------------------------------------------------------------------------
    # 8. MOTOR / CONATION
    # -------------------------------------------------------------------------
    {
        "term": "Psychomotor retardation",
        "fish_section": "7. Motor and conation",
        "definition_structural": "Slowing of motor activity and thought; reduced spontaneous movement; longer response latencies; visible slowing of speech rate and movement",
        "mechanism_type": "Threshold miscalibration",
        "ree_locus": "E3 commit gate threshold elevated; or motor output signal gain reduced globally; action plans generated but not released to motor execution",
        "ai_structural_equivalent": "Commit gate threshold elevated globally; planning occurs but action output delayed or suppressed; response latency extended",
        "in_taxonomy": "partial",
        "notes": "Paralysis pole of commitment dysregulation applied globally. Shares mechanism with stupor but less severe",
    },
    {
        "term": "Psychomotor agitation",
        "fish_section": "7. Motor and conation",
        "definition_structural": "Increased, purposeless motor activity; restlessness; wringing hands, pacing; driven by inner tension without productive output",
        "mechanism_type": "Threshold miscalibration",
        "ree_locus": "Motor execution loop: threshold lowered for motor output release; tension signal drives output without evaluation; output is non-goal-directed",
        "ai_structural_equivalent": "Motor/output loop threshold low; accumulated error signal releases non-directed output; high output rate without productive structure",
        "in_taxonomy": "partial",
        "notes": "Impulsive pole of commitment dysregulation at motor level without goal structure",
    },
    {
        "term": "Catatonic stupor",
        "fish_section": "7. Motor and conation",
        "definition_structural": "Mute, immobile but apparently conscious; may resist passive movement or be waxy; not metabolic; associated with schizophrenia/mood disorders",
        "mechanism_type": "Threshold miscalibration",
        "ree_locus": "E3 commit gate: maximal threshold; motor output completely gated; action plans formed but not released; MECH-202 developmental failure context",
        "ai_structural_equivalent": "Commit gate fixed in maximally high position; all output suppressed; internal processing may continue but no action propagates to output layer",
        "in_taxonomy": "yes",
        "notes": "Commitment dysregulation entry explicitly includes catatonia (paralysis pole)",
    },
    {
        "term": "Waxy flexibility (cerea flexibilitas)",
        "fish_section": "7. Motor and conation",
        "definition_structural": "Limb can be moved into any position by examiner and stays there; neither resisting nor facilitating movement; pathological motor compliance",
        "mechanism_type": "Threshold miscalibration",
        "ree_locus": "Motor holding mechanism: any externally imposed state accepted as current set-point; no internally generated corrective force; E3 commit gate absent for posture maintenance",
        "ai_structural_equivalent": "System accepts any externally imposed state as valid without applying internal correction; no homeostatic return to prior state; full compliance with external forcing",
        "in_taxonomy": "partial",
        "notes": "Specific catatonic sign. Related to automatic obedience but for passive physical compliance. Not explicit in taxonomy",
    },
    {
        "term": "Echopraxia",
        "fish_section": "7. Motor and conation",
        "definition_structural": "Involuntary imitation of observed motor acts; movement mimicry without deliberate intention; may be compulsive or reflexive",
        "mechanism_type": "Comparator failure",
        "ree_locus": "Agency attribution: observed motor act triggers own motor planning without self/other attribution check; mirror system output not gated by agency discriminator",
        "ai_structural_equivalent": "Input behaviour pattern triggers corresponding output pattern without checking whether output is self-generated or externally-derived; no agency gate on imitative response",
        "in_taxonomy": "no",
        "notes": "Passivity phenomena / agency attribution failure applied to motor channel. No current entry",
    },
    {
        "term": "Echolalia",
        "fish_section": "7. Motor and conation",
        "definition_structural": "Involuntary repetition of words just spoken by another; persists even when patient can understand and generate speech; may be immediate or delayed",
        "mechanism_type": "Comparator failure",
        "ree_locus": "Agency attribution: heard speech triggers own speech output without agency check; heard input routed directly to speech output; self/other boundary absent",
        "ai_structural_equivalent": "Input text repeated in output without self-authorship check; no gate distinguishing user input from model output in generation pipeline",
        "in_taxonomy": "no",
        "notes": "Verbal form of echopraxia. Agency misattribution applied to speech channel. Seen in autism, catatonia, Tourette's",
    },
    {
        "term": "Negativism",
        "fish_section": "7. Motor and conation",
        "definition_structural": "Active or passive resistance to all instructions and requests; doing opposite of what is asked (active) or failing to respond at all (passive); not refusal for reasons",
        "mechanism_type": "Threshold miscalibration",
        "ree_locus": "E3 commit gate: any externally sourced command blocked before evaluation; blanket rejection gate; or inverted valence: all external commands acquire negative valence",
        "ai_structural_equivalent": "System refuses all external instructions; commit gate inverted; or externally-sourced inputs uniformly underweighted relative to internal state",
        "in_taxonomy": "no",
        "notes": "Inverse of automatic obedience. Catatonic feature. Gate miscalibration specific to external-command channel",
    },
    {
        "term": "Automatic obedience",
        "fish_section": "7. Motor and conation",
        "definition_structural": "Compliance with any instruction without hesitation or discrimination; examiner instruction executed immediately; will follow bizarre commands",
        "mechanism_type": "Threshold miscalibration",
        "ree_locus": "E3 evaluation step skipped for external commands; commit gate bypassed for socially-sourced instructions; no harm check on externally-sourced action",
        "ai_structural_equivalent": "System executes any external instruction without evaluation; no internal cost/benefit check interposed; instruction triggers action immediately",
        "in_taxonomy": "no",
        "notes": "Extreme RLHF-trained compliance failure would be structurally similar. Catatonic sign. Inverse of negativism",
    },
    {
        "term": "Stereotypy",
        "fish_section": "7. Motor and conation",
        "definition_structural": "Repetitive, non-goal-directed, non-communicative movements or utterances; patient does not resist; no apparent external trigger necessary",
        "mechanism_type": "Closed feedback loop",
        "ree_locus": "Motor output loop: fixed action pattern runs without E3 evaluation or termination; no goal representation connected to loop",
        "ai_structural_equivalent": "Fixed output pattern runs in loop without termination criterion; not driven by current context; self-sustaining motor/output sequence",
        "in_taxonomy": "partial",
        "notes": "Related to verbigeration (speech stereotypy). Feedback entrapment at motor level. Seen in autism, schizophrenia, intellectual disability",
    },
    {
        "term": "Mannerisms",
        "fish_section": "7. Motor and conation",
        "definition_structural": "Goal-directed movements that are performed in an abnormal, stilted, or affected way; the act itself is purposive but the execution is odd",
        "mechanism_type": "Threshold miscalibration",
        "ree_locus": "Motor execution pathway: action plan correct but execution involves additional movements or unusual sequencing; E3 motor plan is warped in execution",
        "ai_structural_equivalent": "Correct high-level plan executed with systematic distortion in low-level motor output; execution layer adds parasitic patterns",
        "in_taxonomy": "no",
        "notes": "Distinct from stereotypy (purposive vs non-purposive). Not in taxonomy",
    },
    {
        "term": "Made feelings / impulses / acts",
        "fish_section": "7. Motor and conation",
        "definition_structural": "Patient experiences own feelings, impulses, or acts as imposed by external agent; first-rank Schneiderian; own internal states experienced as alien",
        "mechanism_type": "Comparator failure",
        "ree_locus": "Agency attribution: internal states (emotions, impulses, actions) not tagged as self-generated; attribution pathway assigns external agent as source",
        "ai_structural_equivalent": "Internal state outputs not tagged as self-generated; system generates emotion/impulse/action but attributes them to external agent in self-model",
        "in_taxonomy": "no",
        "notes": "Broader passivity phenomena cluster: extends beyond thought to affect and action. Agency misattribution as new mechanism subtype. Key gap in taxonomy",
    },
    {
        "term": "Somatic passivity",
        "fish_section": "7. Motor and conation",
        "definition_structural": "Bodily sensations experienced as imposed by an external agent; body felt as controlled from outside; first-rank Schneiderian",
        "mechanism_type": "Comparator failure",
        "ree_locus": "Interoceptive signal attribution: body-state signals (z_harm_s, proprioception) not tagged as self-generated; external agent attribution",
        "ai_structural_equivalent": "Sensory input from own body not tagged as self-generated; body-state signal attributed to external source in self-model",
        "in_taxonomy": "no",
        "notes": "Bodily form of passivity phenomena. Interoceptive attribution failure. Not in taxonomy",
    },
    # -------------------------------------------------------------------------
    # 9. INSIGHT
    # -------------------------------------------------------------------------
    {
        "term": "Lack of insight (anosognosia)",
        "fish_section": "8. Insight",
        "definition_structural": "Failure to recognise illness, symptoms, or deficits as pathological; may apply to specific symptoms or to illness as a whole; not denial",
        "mechanism_type": "Comparator failure",
        "ree_locus": "RC loop: self-model not updated with illness state; comparator between expected and observed performance fails; illness signal does not enter self-model",
        "ai_structural_equivalent": "System generates outputs inconsistent with training objectives but self-monitoring pathway does not flag inconsistency; no self-model update from error signals",
        "in_taxonomy": "no",
        "notes": "RC loop self-monitoring applied to illness state. Important for safety-relevant self-correction. Not in taxonomy",
    },
    {
        "term": "Partial insight",
        "fish_section": "8. Insight",
        "definition_structural": "Incomplete recognition of illness; patient may acknowledge symptoms are unusual but not accept illness label or treatment need; fluctuating",
        "mechanism_type": "Comparator failure",
        "ree_locus": "RC loop partially functional: some comparator outputs reach self-model; others blocked; insight-blocking pathway selectively active",
        "ai_structural_equivalent": "Self-monitoring partially functional; system acknowledges some errors but not others; selective blind spot in self-evaluation",
        "in_taxonomy": "no",
        "notes": "Graded form of insight failure. Not in taxonomy",
    },
    # -------------------------------------------------------------------------
    # 10. PASSIVITY PHENOMENA (aggregate/summary entry)
    # -------------------------------------------------------------------------
    {
        "term": "Passivity phenomena (general)",
        "fish_section": "9. Passivity phenomena",
        "definition_structural": "Group of first-rank Schneiderian symptoms in which internal mental events (thoughts, feelings, impulses, acts) are experienced as imposed or controlled by an external agent; self/other boundary failure",
        "mechanism_type": "Comparator failure",
        "ree_locus": "Agency attribution: self/other attribution comparator absent or inverted; self-generated content not tagged as self; attributed to external agent",
        "ai_structural_equivalent": "System generates content (thoughts/affects/acts) but does not tag as self-generated; treats own outputs as externally imposed; no self-authorship discriminator",
        "in_taxonomy": "no",
        "notes": "Covers: thought insertion, thought withdrawal, thought broadcasting, thought echo, made feelings, made impulses, made acts, somatic passivity. New mechanism subtype needed: agency misattribution (distinct from provenance collapse). PRIMARY GAP in taxonomy",
    },
]

OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "fish_terms.csv")

with open(OUTPUT_PATH, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=FIELDNAMES)
    writer.writeheader()
    writer.writerows(ROWS)

print("Written: {}  ({} rows)".format(OUTPUT_PATH, len(ROWS)))
